### ISSUE TITLE
ImportError: No module named web

### ISSUE THREAD

**Issue by DSoa** [philogb/jit#163]
I'm having trouble with the commands to build the examples on Windows.  I'm using  Python 2.7 on Windows 7.

```
C:\jit>python make.py build
Traceback (most recent call last):
  File "make.py", line 6, in <module>
    from serve import render
  File "C:\jit\serve.py", line 1, in <module>
    import web
ImportError: No module named web
```

I tried adding c:\jit to my PATH env var, and to PYTHONPATH, to no avail.

Can someone please tell me how to get this to run?

Thanks.

**Comment by clairian** [comment]
Hi - did you ever get to the bottom of this issue? i'm trying to run Jit for the first time and am facing the same error.

Thanks

**Comment by DSoa** [comment]
no

**Comment by k3d3** [comment]
It's because the `web` directory is a symbolic link to `webpy/web`. Windows tends not to support symbolic links with git, and so the web directory appears broken.

As a workaround, just copy `webpy/web` to `web`, and it should work again.
